name: Monitor External Release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

env:
  TARGET_REPO: ${{ vars.TARGET_REPOSITORY }}
  MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}

jobs:
  watch-release:
    runs-on: ubuntu-latest
    steps:
      - name: 設定検証
        run: |
          set -euo pipefail
          if [ -z "$TARGET_REPO" ]; then
            echo "Vars.TARGET_REPOSITORY が未設定です" >&2
            exit 1
          fi
          if [ -z "$MATTERMOST_WEBHOOK_URL" ]; then
            echo "Secrets.MATTERMOST_WEBHOOK_URL が未設定です" >&2
            exit 1
          fi

      - name: 最新リリース取得
        id: fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          tmp_json=$(mktemp)
          status=$(curl -sS -w '%{http_code}' \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o "$tmp_json" \
            "https://api.github.com/repos/${TARGET_REPO}/releases/latest")

          if [ "$status" -eq 404 ]; then
            echo "release_found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ "$status" -ne 200 ]; then
            echo "GitHub API error: HTTP $status" >&2
            cat "$tmp_json" >&2 || true
            exit 1
          fi

          tag=$(jq -r '.tag_name // empty' "$tmp_json")
          if [ -z "$tag" ]; then
            echo "release_found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          name=$(jq -r '.name // empty' "$tmp_json")
          url=$(jq -r '.html_url // empty' "$tmp_json")
          body=$(jq -r '.body // empty' "$tmp_json")

          {
            echo "release_found=true"
            printf 'tag=%s\n' "$tag"
            printf 'name=%s\n' "$name"
            printf 'url=%s\n' "$url"
            printf 'body<<EOF\n%s\nEOF\n' "$body"
          } >> "$GITHUB_OUTPUT"

      - name: 状態読み込み・初期化
        if: steps.fetch.outputs.release_found == 'true'
        id: state
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          label="release-monitor"
          tmp=$(mktemp)
          status=$(curl -sS -w '%{http_code}' \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o "$tmp" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?labels=${label}&state=open&per_page=1")

          if [ "$status" -ne 200 ]; then
            echo "GitHub API error: HTTP $status" >&2
            cat "$tmp" >&2 || true
            exit 1
          fi

          issue_number=$(jq -r '.[0].number // empty' "$tmp")
          issue_body=$(jq -r '.[0].body // empty' "$tmp")

          if [ -z "$issue_number" ]; then
            state_json='{"last_tag":""}'
            create_payload=$(jq -n \
              --arg title "External Release Monitor State" \
              --arg body "$state_json" \
              --arg label "$label" \
              '{title:$title, body:$body, labels:[$label]}')

            tmp_create=$(mktemp)
            status=$(curl -sS -w '%{http_code}' \
              -H 'Accept: application/vnd.github+json' \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H 'Content-Type: application/json' \
              -o "$tmp_create" \
              -d "$create_payload" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues")

            if [ "$status" -ne 201 ]; then
              echo "GitHub API error: HTTP $status" >&2
              cat "$tmp_create" >&2 || true
              exit 1
            fi

            issue_number=$(jq -r '.number' "$tmp_create")
            issue_body=$(jq -r '.body // empty' "$tmp_create")
          fi

          last_tag=$(printf '%s' "$issue_body" | jq -r 'try fromjson catch {} | .last_tag // ""')

          {
            printf 'issue_number=%s\n' "$issue_number"
            printf 'last_tag=%s\n' "$last_tag"
          } >> "$GITHUB_OUTPUT"

      - name: 新規リリース判定
        if: steps.fetch.outputs.release_found == 'true'
        id: compare
        env:
          LATEST_TAG: ${{ steps.fetch.outputs.tag }}
          LAST_TAG: ${{ steps.state.outputs.last_tag }}
        run: |
          set -euo pipefail
          if [ "$LATEST_TAG" = "$LAST_TAG" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Mattermostメッセージ生成
        if: steps.compare.outputs.changed == 'true'
        id: message
        env:
          TARGET_REPO: ${{ env.TARGET_REPO }}
          RELEASE_TAG: ${{ steps.fetch.outputs.tag }}
          RELEASE_NAME: ${{ steps.fetch.outputs.name }}
          RELEASE_URL: ${{ steps.fetch.outputs.url }}
          RELEASE_BODY: ${{ steps.fetch.outputs.body }}
        run: |
          python - <<'PY'
import json
import os

target_repo = os.environ['TARGET_REPO']
release_tag = os.environ.get('RELEASE_TAG', 'unknown')
release_name = os.environ.get('RELEASE_NAME') or release_tag
release_url = os.environ.get('RELEASE_URL', '')
release_body = os.environ.get('RELEASE_BODY') or ''

lines = [
    f"External release `{release_tag}` detected for *{target_repo}*",
    f"Title: {release_name}",
    f"URL: {release_url}",
]

if release_body.strip():
    lines.append('\n```markdown')
    lines.append(release_body)
    lines.append('```')

payload = json.dumps({"text": '\n'.join(lines)})

with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as fh:
    fh.write('payload<<EOF\n')
    fh.write(payload)
    fh.write('\nEOF\n')
PY

      - name: Mattermostへ送信
        if: steps.compare.outputs.changed == 'true'
        run: |
          curl -sS -X POST \
            -H 'Content-Type: application/json' \
            -d '${{ steps.message.outputs.payload }}' \
            "$MATTERMOST_WEBHOOK_URL"

      - name: 状態更新
        if: steps.compare.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.state.outputs.issue_number }}
          LATEST_TAG: ${{ steps.fetch.outputs.tag }}
        run: |
          set -euo pipefail
          state_json=$(jq -n --arg tag "$LATEST_TAG" '{last_tag:$tag}')
          payload=$(jq -n --arg body "$state_json" '{body:$body}')

          tmp=$(mktemp)
          status=$(curl -sS -w '%{http_code}' \
            -X PATCH \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H 'Content-Type: application/json' \
            -o "$tmp" \
            -d "$payload" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}")

          if [ "$status" -ne 200 ]; then
            echo "GitHub API error: HTTP $status" >&2
            cat "$tmp" >&2 || true
            exit 1
          fi
