name: Monitor External Release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  TARGET_REPO: ${{ vars.TARGET_REPOSITORY }}
  MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}

jobs:
  watch-release:
    runs-on: ubuntu-latest
    steps:
      - name: 設定検証
        run: |
          set -euo pipefail
          if [ -z "$TARGET_REPO" ]; then
            echo "Vars.TARGET_REPOSITORY が未設定です" >&2
            exit 1
          fi
          if [ -z "$MATTERMOST_WEBHOOK_URL" ]; then
            echo "Secrets.MATTERMOST_WEBHOOK_URL が未設定です" >&2
            exit 1
          fi

      - name: 最新リリース取得
        id: fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          tmp_json=$(mktemp)
          status=$(curl -sS -w '%{http_code}' \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o "$tmp_json" \
            "https://api.github.com/repos/${TARGET_REPO}/releases/latest")

          if [ "$status" -eq 404 ]; then
            echo "release_found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ "$status" -ne 200 ]; then
            echo "GitHub API error: HTTP $status" >&2
            cat "$tmp_json" >&2 || true
            exit 1
          fi

          tag=$(jq -r '.tag_name // empty' "$tmp_json")
          if [ -z "$tag" ]; then
            echo "release_found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          name=$(jq -r '.name // empty' "$tmp_json")
          url=$(jq -r '.html_url // empty' "$tmp_json")
          body=$(jq -r '.body // empty' "$tmp_json")

          {
            echo "release_found=true"
            printf 'tag=%s\n' "$tag"
            printf 'name=%s\n' "$name"
            printf 'url=%s\n' "$url"
            printf 'body<<EOF\n%s\nEOF\n' "$body"
          } >> "$GITHUB_OUTPUT"

      - name: 前回通知済みタグ取得
        if: steps.fetch.outputs.release_found == 'true'
        id: previous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          tmp_json=$(mktemp)
          status=$(curl -sS -w '%{http_code}' \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o "$tmp_json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/variables/LAST_SEEN_RELEASE")

          if [ "$status" -eq 404 ]; then
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "last_tag=" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ "$status" -ne 200 ]; then
            echo "GitHub API error: HTTP $status" >&2
            cat "$tmp_json" >&2 || true
            exit 1
          fi

          last=$(jq -r '.value // empty' "$tmp_json")
          {
            echo "exists=true"
            printf 'last_tag=%s\n' "$last"
          } >> "$GITHUB_OUTPUT"

      - name: 新規リリース判定
        if: steps.fetch.outputs.release_found == 'true'
        id: compare
        env:
          LATEST_TAG: ${{ steps.fetch.outputs.tag }}
          LAST_TAG: ${{ steps.previous.outputs.last_tag }}
        run: |
          set -euo pipefail
          if [ "$LATEST_TAG" = "$LAST_TAG" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Mattermostメッセージ生成
        if: steps.compare.outputs.changed == 'true'
        id: message
        env:
          TARGET_REPO: ${{ env.TARGET_REPO }}
          RELEASE_TAG: ${{ steps.fetch.outputs.tag }}
          RELEASE_NAME: ${{ steps.fetch.outputs.name }}
          RELEASE_URL: ${{ steps.fetch.outputs.url }}
          RELEASE_BODY: ${{ steps.fetch.outputs.body }}
        run: |
          set -euo pipefail
          release_title="$RELEASE_NAME"
          if [ -z "$release_title" ]; then
            release_title="$RELEASE_TAG"
          fi

          text="External release \\`$RELEASE_TAG\\` detected for *$TARGET_REPO*\n"
          text+="Title: $release_title\n"
          text+="URL: $RELEASE_URL"

          if [[ -n "${RELEASE_BODY//[[:space:]]/}" ]]; then
            text+="\n\n\\`\\`\\`markdown\n$RELEASE_BODY\n\\`\\`\\`"
          fi

          payload=$(jq -n --arg text "$text" '{text: $text}')

          {
            echo "payload<<EOF"
            printf '%s\n' "$payload"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Mattermostへ送信
        if: steps.compare.outputs.changed == 'true'
        run: |
          curl -sS -X POST \
            -H 'Content-Type: application/json' \
            -d '${{ steps.message.outputs.payload }}' \
            "$MATTERMOST_WEBHOOK_URL"

      - name: 最終通知タグ更新
        if: steps.compare.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_TAG: ${{ steps.fetch.outputs.tag }}
          VARIABLE_EXISTS: ${{ steps.previous.outputs.exists }}
        run: |
          set -euo pipefail
          data=$(jq -n --arg value "$LATEST_TAG" '{name:"LAST_SEEN_RELEASE", value:$value}')
          url="https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/variables"

          if [ "$VARIABLE_EXISTS" = "true" ]; then
            curl -sS -X PATCH \
              -H 'Accept: application/vnd.github+json' \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H 'Content-Type: application/json' \
              -d "$data" \
              "$url/LAST_SEEN_RELEASE" >/dev/null
          else
            curl -sS -X POST \
              -H 'Accept: application/vnd.github+json' \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H 'Content-Type: application/json' \
              -d "$data" \
              "$url" >/dev/null
          fi
